# -*- coding: utf-8 -*-
"""To_Do_List

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/154Yh72tJydrDN0bAiOTNoLUrqY6FU0i5
"""

import json

# Lists
my_tasks = []
completed_tasks = []

# Functions
def save_tasks():
    data = {
        "pending_tasks": my_tasks,
        "completed_tasks": completed_tasks
    }
    with open("tasks.json", "w") as file:
        json.dump(data, file)
    print("Tasks saved successfully!")

def read_tasks():
    global my_tasks, completed_tasks
    try:
        with open("tasks.json", "r") as file:
            data = json.load(file)
            my_tasks = data["pending_tasks"]
            completed_tasks = data["completed_tasks"]
        print("Tasks loaded successfully!")
    except FileNotFoundError:
        print("No saved file found!")


def view_tasks():
    print("\n===== Pending Tasks =====")
    if len(my_tasks) == 0:
        print("No pending tasks.")
    else:
        for index, task in enumerate(my_tasks):
            print(f"{index} : {task}")

    print("\n===== Completed Tasks =====")
    if len(completed_tasks) == 0:
        print("No completed tasks.")
    else:
        for index, task in enumerate(completed_tasks):
            print(f"{index} : {task}")

# Main Program
while True:
    print("""
1. Add Task
2. View Tasks
3. Delete Task
4. Edit Task
5. Complete Task
6. Save Tasks
7. Load Tasks
8. Exit
""")

    choice = input("Enter your choice: ")

    # Add Task
    if choice == "1":
        task = input("Enter your task: ")
        my_tasks.append(task)
        print("Task added successfully!")

    # View Tasks
    elif choice == "2":
        view_tasks()

    # Delete Task
    elif choice == "3":
        if len(my_tasks) == 0:
            print("No tasks available!")
        else:
            view_tasks()
            try:
                index = int(input("Enter task index to delete: "))
                deleted_task = my_tasks.pop(index)
                print(f"Deleted task: {deleted_task}")
            except:
                print("Invalid index!")

    # Edit Task
    elif choice == "4":
        if len(my_tasks) == 0:
            print("No tasks available!")
        else:
            view_tasks()
            try:
                index = int(input("Enter task index to edit: "))
                new_task = input("Enter new task: ")
                my_tasks[index] = new_task
                print("Task updated successfully!")
            except:
                print("Invalid index!")

    # Complete Task
    elif choice == "5":
        if len(my_tasks) == 0:
            print("No tasks available!")
        else:
            view_tasks()
            try:
                index = int(input("Enter completed task index: "))
                completed = my_tasks.pop(index)
                completed_tasks.append("✔ " + completed)
                print("Task marked as completed!")
            except:
                print("Invalid index!")

    # Save Tasks
    elif choice == "6":
        save_tasks()

    # Load Tasks
    elif choice == "7":
        read_tasks()

    # Exit
    elif choice == "8":
        print("Exiting program...")
        break

    # Invalid Choice
    else:
        print("Invalid choice! Please try again.")