# -*- coding: utf-8 -*-
"""Variables_datatypes_methods

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k7Ku_96S0nlz7YBcrvs5RLtE8JHQTSMm

##variables
"""

#variables
name = "fozia"      #string
age = 19            #integer
weight = 40.0       #float
is_active = True    #boolen
nothing_here = None #boolen

"""##display all variables and its data types"""

#display all variables and its data types
print("name \t:", name , type(name))
print("Age \t:", age , type(age))
print("weight \t:", weight, type(weight))
print("is active \t:", is_active, type(is_active))
print("Check none type :", nothing_here, type(nothing_here))

"""###slicing practice"""

#slicing practice
name = "This is my program"
print(len(name))
print(name[0:]) # means its [0:19]
print(name[:19]) # means its [0:19]
print(name[0:-1])
print(name[-18:-1])
print(name[-18:19])
print(name[::-1]) #reverse
print(name[::-2]) # 1 digit short reverse
name1 = "hello world"
print(name1[::-1])
name2 = "wow moom"
print(name2[::-1])

#odd numbers
num = (1,2,3,4,5,6,7,8,9,10,11)
print(num[::2])

#even numbers
num1 = (0,1,2,3,4,5,6,7,8,9,10,11,12)
print(num1[::2])

"""##Check String is mutable or not"""

#string is immutable we cannot change
try:
  name[0] = "A"
except TypeError:
  print("'str' object does not support item assignment")

name = "I am fozia and i learn   python "
print(name.find("  ")) #find space

print(name.replace("  ", "")) #replace double space into single space
print(name) #string are imutable thats mean they cannot chsngr when run in function but create new string

"""#Type conversion"""

num1 = 10
num2 = "19"

print(num1 + int(num2))  #change type

int(23.4), int(False), int(True), int("34")

float(98), float(True), float('45')

bool(1), bool(0), bool("5")  #in bool ) consider false other are true

x = (8 + True) #boolean value are scts as integer
y = (6 + False)

print(x) #ture - 1
print(y) #false - 0

"""##User define or predefine input"""

x = 56 # predefine input - we already define input
print(x)

y = input("enter the number:") # userdefine input - ask user to define input when it runs
print(y)

"""##String fomarts"""

product = "cream"
price = 300
quantity = 12

#f formating
print(f"product is {product}. its price is {price} and its quantity is {quantity}")

# . fomating with indexing
print("product is {0}. its price is {1} and its quantity is {2}".format (product, price, quantity))

# , fomarting
print("product is", product,"its price is ",price, "and its quantity is", quantity)

#Concatination only str + str
print("product is" + (product) + "its price is "+ str(price) + "and its quantity is"+ str(quantity))

"""##Practice on predeine functions
* count , split , join , strip, find start/end with , indexing , slicing , isdigit , isalpha isalnum , replace
"""

sen = ("I love python")

#count
print("count: ",sen.count("o"))
#split
print("\nSplit: ",sen.split(" "))
print("Split: ",sen.split(","))
print("Split: ",sen.split("."))
#join
print("\nJoin: ", " ".join (sen))
print("Join: ", ",".join (sen))
print("Join: ", "-".join (sen))
print("Join: ", ".".join (sen))
print("Join: ", "*".join (sen))
#find
print("\nFind: ",sen.find("I"))
print("Find: ",sen.find("python"))
#starts/ends with
print("\nStarts with: ",sen.startswith("I"))
print("Ends with: ",sen.endswith("python"))
print("Ends with: ",sen.endswith("n"))
#indexing
print("\nIndexing: ",sen[0])
print("Indexing: ",sen[-1])
print("Indexing: ",sen[4])
#slicing
print("Slicing: ",sen[1:6])
#Reverse
print("Reverse: ",sen[::-1])

a = ("   python   ")
print("strip:",a.strip(" "))

sen2 = ("i am 18 year old")
n = ("python")
b = ("23")
print(sen2.isalpha())
print(a.isalpha())
print(n.isalpha())
print(sen2.isdigit())
print(b.isdigit())
print(sen2.isalnum())
print(sen2.replace("i", "I"))